name: penpot-plugin

services:
  template-api:
    image: oculair/penpot-template-api:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - penpot-plugins-net
    labels:
      - com.docker.compose.project=penpot-plugins
      - com.docker.compose.service=template-api
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - require("http").get("http://localhost:3000/manifest.json", (res) => {
          if (res.statusCode !== 200) { process.exit(1) } });
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  penpot-plugins-net:
    name: penpot_plugin_network
    driver: bridge